#!/bin/sh /etc/rc.common
# Copyright (C) 2015 OpenWrt.org

START=99


start()
{

	sleep 30
        [ -f /root/AnySense_7688/APP_Harvard_TX.py ] && {
                /usr/bin/git --git-dir=/root/AnySense_7688/.git pull origin master
		/usr/bin/python /root/AnySense_7688/AnySense_RTC.py &>/dev/null
		/usr/bin/python /root/AnySense_7688/APP_Harvard_TX.py &>/dev/null
        } || {
                /usr/bin/git clone https://github.com/cclljj/AnySense_7688 /root/AnySense_7688
		/usr/bin/python /root/AnySense_7688/AnySense_RTC.py &>/dev/null
		/usr/bin/python /root/AnySense_7688/APP_Harvard_TX.py &>/dev/null
        }


}

stop()
{
        [ -f /root/AnySense_7688/APP_Harvard_TX.py ] && {
		rm -rf /root/AnySense_7688
	}
}
