#!/bin/sh /etc/rc.common
# Copyright (C) 2015 OpenWrt.org

START=99


start()
{

	sleep 10
        [ -f /root/AnySense_7688/IAQ_NBIOT_Lite_CHT.py ] && {
		/usr/bin/git -C /root/AnySense_7688 fetch origin
		/usr/bin/git -C /root/AnySense_7688 reset --hard origin/master
		/usr/bin/python /root/AnySense_7688/AnySense_RTC.py &>/dev/null
		/usr/bin/python /root/AnySense_7688/IAQ_NBIOT_Lite_CHT.py &>/dev/null
        } || {
        /usr/bin/git clone https://github.com/SCWhite/AnySense_7688/ /root/AnySense_7688
		/usr/bin/python /root/AnySense_7688/AnySense_RTC.py &>/dev/null
		/usr/bin/python /root/AnySense_7688/IAQ_NBIOT_Lite_CHT.py &>/dev/null
        }


}

stop()
{
        [ -f /root/AnySense_7688/IAQ_NBIOT_Lite_CHT.py ] && {
		rm -rf /root/AnySense_7688
	}
}
